// Click&Clean for Google Chrome - HOTCLEANER.COM - Copyright (c) 2017 Vlad & Serge Strukoff. All Rights Reserved.
var _vd={configurable:!1,enumerable:!1,writable:!1,value:{}};
(function(d,l,da,z,ea){function fa(){function a(c,h){for(var f,e,d=0,r=h.length;d<r;d++)if(node=h[d],1==node.t){f=node.n?ha.call(l,NAMESPACE_SVG,node.l):A.call(l,node.l);for(var u=0,k=node.a&&node.a.length||0;u<k;u++)e=node.a[u],w.call(f,e.n,e.v);node.c&&a(f,node.c);t.call(c,f)}else 3==node.t&&t.call(c,Q.call(l,node.v))}var c=ia('[{"t":1,"l":"link","a":[{"n":"rel","v":"stylesheet"},{"n":"type","v":"text/css"},{"n":"href","v":"css/qkWf.css"}]},{"t":1,"l":"div","a":[{"n":"id","v":"host"}],"c":[{"t":1,"l":"div","a":[{"n":"class","v":"view"},{"n":"id","v":"view0"}],"c":[{"t":1,"l":"div","a":[{"n":"class","v":"hdr"},{"n":"id","v":"hdr0"}],"c":[{"t":1,"l":"button","a":[{"n":"id","v":"sel0"},{"n":"class","v":"chk"},{"n":"title","v":"t10"}],"c":[{"t":1,"l":"div"}]},{"t":1,"l":"label","a":[{"n":"class","v":"label elps"},{"n":"id","v":"t11"}],"c":[{"t":1,"l":"span","a":[{"n":"id","v":"cnt0"}]}]},{"t":1,"l":"button","a":[{"n":"class","v":"btn"},{"n":"id","v":"del0"},{"n":"title","v":"t14"}]},{"t":1,"l":"button","a":[{"n":"class","v":"btn"},{"n":"id","v":"ref"},{"n":"title","v":"t13"}]}]},{"t":3,"v":" "},{"t":1,"l":"div","a":[{"n":"class","v":"list"},{"n":"id","v":"list0"},{"n":"data-id","v":"0"}]}]},{"t":1,"l":"button","a":[{"n":"id","v":"toc1"}]},{"t":1,"l":"button","a":[{"n":"id","v":"toc0"}]},{"t":1,"l":"div","a":[{"n":"class","v":"view"},{"n":"id","v":"view1"}],"c":[{"t":1,"l":"div","a":[{"n":"class","v":"hdr"},{"n":"id","v":"hdr1"}],"c":[{"t":1,"l":"button","a":[{"n":"id","v":"sel1"},{"n":"class","v":"chk"},{"n":"title","v":"t10"}],"c":[{"t":1,"l":"div"}]},{"t":1,"l":"label","a":[{"n":"class","v":"label elps"},{"n":"id","v":"t12"}],"c":[{"t":1,"l":"span","a":[{"n":"id","v":"cnt1"},{"n":"class","v":"nvw"}]}]},{"t":1,"l":"div","a":[{"n":"id","v":"services"}]}]},{"t":1,"l":"div","a":[{"n":"class","v":"list"},{"n":"id","v":"list1"},{"n":"data-id","v":"1"}]}]},{"t":1,"l":"div","a":[{"n":"id","v":"shade"}]}]}]');B=
L&&53<M?L.call(l.body,{mode:"closed"}):l.body;var h=R.call(l);a(h,c);t.call(B,h)}function ja(){function a(){C(1);for(var b=h("#list0");b.firstElementChild;)E.call(b,b.firstElementChild);for(b=h("#list1");b.firstElementChild;)E.call(b,b.firstElementChild);F(G({id:30}),function(b){var a=b[0];b=b[1];var q=[],p=0,c=0,g=0;if(0<a.length){for(var f=0,e;e=a[f];f++)"."==e.charAt(0)&&(a[f]=T.call(e,1));ka.call(a,function(b,a){return b<a?-1:1});var d=V.call(b,a[0]);for(f=0;e=a[f];f++){l!=e&&(0<p&&(0>d?(H.call(q,
p),c+=p):(b[d+1]=p,g+=p),p=0),d=V.call(b,e),0>d&&H.call(q,e));p++;var l=e}0<p&&(0>d?(H.call(q,p),c+=p):(b[d+1]=p,g+=p))}K(0,q,1,1);K(1,b,0,0);h("#cnt0").textContent=" ("+c+")";h("#cnt1").textContent=" ("+g+")";C(0)})}function c(b){b=B(this,"on");for(var a=this.parentElement.nextElementSibling.children,m=0,c;c=a[m];m++)N(c.firstElementChild,"on",b),N(c,"on",b)}function e(b){var a=f.call(this.parentNode,"data-domain");F(G({id:9,v:"https://"+a+"/"}));W.call(b)}function d(b){W.call(b);b=this.parentNode;
var a=f.call(b.parentNode,"data-id"),m=f.call(b,"data-domain"),c=I(f.call(b,"data-count"));F(G({id:32,v:[m]}));E.call(b.parentElement,b);y(a,-c);1==a&&x()}function k(b){C(1);var a=this.parentElement.nextElementSibling;b=X.call(a,".item[on]");if(0<b.length){var m=[];a=f.call(a,"data-id");for(var c,p=0,e=0,g;g=b[e];e++)c=f.call(g,"data-domain"),H.call(m,c),p+=I(f.call(g,"data-count")),E.call(g.parentElement,g);F(G({id:32,v:m}));y(a,-p)}C(0)}function v(){C(1);D(1,0);x()}function z(b){C(1);D(0,1);x()}
function x(){for(var b=[],a=h("#list1").children,m=0,c;c=a[m];m++)H.call(b,f.call(c,"data-domain"),0);F(G({id:35,v:b}));C(0)}function D(a,c){var b=X.call(h("#list"+a),".item[on]");if(0<b.length){for(var q=[],p=0,e;e=b[p];p++)H.call(q,E.call(e.parentNode,e));M(a,c,q)}}function y(a,c){a=h("#cnt"+a);var b=I(T.call(a.textContent,2));a.textContent=" ("+(b+c)+")"}function B(a,c){var b=Y.call(a,c);b?Z.call(a,c):w.call(a,c,!0);return!b}function N(a,c,m){m?w.call(a,c,!0):Z.call(a,c)}function L(a){var b=Y.call(this,
"on");if(a.shiftKey){if(0>O&&(O=this.parentNode.firstElementChild),a=!b,b=O,this&&b){var c=this;f.call(c,"data-domain")>f.call(b,"data-domain")&&(c=b,b=this);for(;c&&f.call(c,"data-domain")<=f.call(b,"data-domain");)N(c,"on",a),N(c.firstElementChild,"on",a),c=c.nextElementSibling}}else B(this.firstElementChild,"on"),B(this,"on");O=this}function J(a,c,m,h){var b=A.call(l,"div");var f=A.call(l,"button");var g=A.call(l,"div");var q=A.call(l,"label");var S=A.call(l,"button");var k=A.call(l,"button");
b.className="item";f.className="chk";q.className="label elps";k.className="btn link";S.className="btn del";w.call(b,"data-domain",a);w.call(b,"data-count",c);h&&(w.call(f,"on",!0),w.call(b,"on",!0));q.textContent=a+(m?" ("+c+")":"");t.call(f,g);t.call(b,f);t.call(b,q);t.call(b,S);t.call(b,k);r.call(S,"click",d,!1);r.call(k,"click",e,!1);r.call(b,"click",L,!1);return b}function K(a,c,e,f){a=h("#list"+a);for(var b,m=R.call(l),g=0;b=c[g];g+=2)b=J(b,c[g+1],e,f),t.call(m,b);t.call(a,m)}function M(a,c,
e){for(var b=h("#list"+c),m,d,g,q=0,l=0,k;k=e[l];l++){g=!0;m=f.call(k,"data-domain");for(var r=0,u;u=b.children[r];r++)if(d=f.call(u,"data-domain"),m==d){g=!1;break}else if(m<d){g=I(f.call(k,"data-count"));q+=g;d=k.firstElementChild.nextElementSibling;d.textContent=0==c?m+" ("+g+")":m;U.call(b,k,u);g=!1;break}g&&(g=I(f.call(k,"data-count")),q+=g,d=k.firstElementChild.nextElementSibling,d.textContent=0==c?m+" ("+g+")":m,t.call(b,k))}0<q&&(y(a,-q),y(c,q))}function P(a){for(var b,c=0;2>c;c++)if(a=f.call(this,
"data-d"+c)){a:{for(var e,d=a,k=h("#list0").children,g=0;b=k[g];g++)if(e=f.call(b,"data-domain"),e==d)break a;b=0}b=b?E.call(b.parentNode,b):J(a,0,0,1);M(0,1,[b])}x()}function C(a){h("#shade").className=a?"dbk":"nvw"}var O=-1;F(G({id:2}),function(b){a:{for(var e=[la(""),"https://www.hotcleaner.com/"],d=0,f=e.length;d<f;d++)if(0==aa.call(b,e[d]))break a;l.location.href="about:blank"}b=ma.call(ea.getMessage("cookies"),";");el=h("#sel0");el.title=b[0];el=h("#sel1");el.title=b[0];el=h("#t11");U.call(el,
Q.call(l,b[1]),el.firstElementChild);el=h("#t12");U.call(el,Q.call(l,b[2]),el.firstElementChild);el=h("#ref");el.title=b[3];el=h("#del0");el.title=b[4];r.call(h("#sel0"),"click",c,!1);r.call(h("#sel1"),"click",c,!1);r.call(h("#ref"),"click",a,!1);r.call(h("#del0"),"click",k,!1);r.call(h("#toc0"),"click",v,!1);r.call(h("#toc1"),"click",z,!1);a();b=h("#services");e=[{n:"Google | G+, GMail, YouTube, ...",d0:"accounts.google.com",d1:"google.com",i:1},{n:"Facebook",d0:"facebook.com",i:2},{n:"Twitter",
d0:"twitter.com",i:3},{n:"Yahoo",d0:"yahoo.com",i:4},{n:"Microsoft | SkyDrive, Live Mail, ...",d0:"login.live.com",d1:"live.com",i:5}];for(var p=R.call(l),u=0,g;g=e[u];u++)d=A.call(l,"button"),d.className="btn float-left",d.title=g.n,w.call(d,"data-d0",g.d0),g.d1&&w.call(d,"data-d1",g.d1),f=new Image,f.className="mt3",f.src="i/fav/"+g.i+".png",t.call(d,f),r.call(d,"click",P,!1),t.call(p,d);t.call(b,p)})}function h(a){return L&&53<M?na.call(B,a):oa.call(l,a)}function a(){}var la=z.getURL,F=z.sendMessage;
z=String.prototype;var J=Array.prototype,x=Storage.prototype,pa=Navigator.prototype,qa=XMLHttpRequest.prototype,K=DocumentFragment.prototype,e=Document.prototype,P=DOMImplementation.prototype,D=EventTarget.prototype,y=Event.prototype,k=Node.prototype,c=Element.prototype,ba=HTMLElement.prototype,ra=HTMLMediaElement.prototype,T=z.slice,aa=z.indexOf,ma=z.split,V=J.indexOf,H=J.push,ka=J.sort,A=e.createElement,ha=e.createElementNS,r=D.addEventListener,R=e.createDocumentFragment,Y=c.hasAttribute,f=c.getAttribute,
w=c.setAttribute,Z=c.removeAttribute,Q=e.createTextNode,W=y.stopPropagation,t=k.appendChild,U=k.insertBefore,E=k.removeChild,L=c.attachShadow||void 0,X=c.querySelectorAll,na=K.querySelector,oa=e.querySelector;try{var v=Object.getOwnPropertyDescriptor(Function.prototype,"apply");v&&(v.configurable=!1,v.writable=!1,Object.defineProperty(Function.prototype,"apply",v))}catch(u){}try{if(v=Object.getOwnPropertyDescriptor(Function.prototype,"call"))v.configurable=!1,v.writable=!1,Object.defineProperty(Function.prototype,
"call",v)}catch(u){}x.getItem=a;x.setItem=a;x.removeItem=a;x.clear=a;pa.sendBeacon=a;qa.open=a;K.querySelector=a;K.querySelectorAll=a;e.createDocumentFragment=a;e.createTextNode=a;e.createElement=a;e.createElementNS=a;e.evaluate=a;e.createEvent=a;e.createCDATASection=a;e.execCommand=a;e.querySelector=a;e.querySelectorAll=a;e.write=a;e.writeln=a;P.createHTMLDocument=a;P.createDocument=a;D.addEventListener=a;D.removeEventListener=a;D.dispatchEvent=a;y.preventDefault=a;y.stopPropagation=a;y.stopImmediatePropagation=
a;k.appendChild=a;k.cloneNode=a;k.getRootNode=a;k.removeChild=a;k.replaceChild=a;k.insertBefore=a;c.attachShadow=a;c.createShadowRoot=a;c.getElementsByClassName=a;c.getElementsByTagName=a;c.getElementsByTagNameNS=a;c.append=a;c.remove=a;c.before=a;c.after=a;c.prepend=a;c.querySelector=a;c.querySelectorAll=a;c.requestPointerLock=a;c.setAttribute=a;c.removeAttribute=a;c.removeAttributeNS=a;c.removeAttributeNode=a;c.replaceWith=a;c.insertAdjacentElement=a;c.insertAdjacentText=a;c.insertAdjacentHTML=
a;ba.focus=a;ba.click=a;ra.play=a;var G=d.JSON.stringify,ia=d.JSON.parse,I=d.parseInt,sa=d.setTimeout,ca=da.userAgent,M=function(){var a=aa.call(ca,"Chrome/");return-1<a?I(T.call(ca,a+7)):0}(),B;r.call(d,"DOMContentLoaded",function(){fa();sa(function(){l.title="Cookies"},1E3);ja()},!0)})(window,document,navigator,chrome.runtime,chrome.i18n);
for(var i in chrome)if("runtime"==i)for(var n in chrome.runtime)"function"===typeof chrome.runtime[n]&&"connect"!==n&&(chrome.runtime[n]=function(){});else if("object"===typeof chrome[i])try{Object.defineProperty(chrome,i,_vd)}catch(d){}try{Object.defineProperty(window,"localStorage",_vd)}catch(d){}try{Object.defineProperty(window,"navigator",_vd)}catch(d){}try{Object.defineProperty(window,"XMLHttpRequest",_vd)}catch(d){}try{Object.defineProperty(window,"JSON",_vd)}catch(d){}
try{Object.defineProperty(window,"fetch",_vd)}catch(d){}try{Object.defineProperty(Document.prototype,"cookie",_vd)}catch(d){}try{Object.defineProperty(Element.prototype,"innerHTML",_vd)}catch(d){}try{Object.defineProperty(Element.prototype,"outerHTML",_vd)}catch(d){}try{Object.defineProperty(HTMLElement.prototype,"innerText",_vd)}catch(d){}try{Object.defineProperty(Element.prototype,"outerText",_vd)}catch(d){};
