// Click&Clean for Google Chrome - HOTCLEANER.COM - Copyright (c) 2017 Vlad & Serge Strukoff. All Rights Reserved.
var _vd={configurable:!1,enumerable:!1,writable:!1,value:{}};
(function(e,q,F,k,Q,A,N){function C(){var e=S.call(G,"Chrome/");return-1<e?H(U.call(G,e+7)):0}function V(){function m(){var b=this.id;p!=b&&(p&&(x(p).className="nav"),p=b,this.className="nav act",k(b))}function k(b){var a=x("box");if("menu0"==b)var y=[3,"red","close.png",0,7,0,"options1.png",18,3,"magenta","clear.png",1,7,0,"options1.png",18,7,0,"tabs1.png",2,3,"violet","cache.png",3,7,0,"trash1.png",4,3,"violet","history.png",5,7,0,"trash1.png",6,0,"blue",w?"quickscan.png":"extensions.png",w?8:7,
3,"violet","downloads.png",9,7,0,"trash1.png",10,0,"choko","cookie.png",15,7,0,"trash1.png",16,0,"seawave",w?"cleanup.png":"memory.png",w?12:13,3,"violet","security.png",14,0,"carbon","incognito.png",11,0,"teal","report.png",17,0,"magenta","options.png",18,7,0,"themes.png",19,0,"green","updates.png",20,0,"yellow","rate32.png",21];else if("menu1"==b)y=[3,"seawave","plugins.png",0,3,"green","extensions.png",1,3,"orange","experiments.png",2,3,"magenta","internals.png",3,0,"violet","dns.png",4,3,"violet",
"history.png",5,0,"violet","cache.png",6,0,"red","key.png",7,3,"blue","version.png",8,7,0,"arrow1.png",9,0,"red","conflicts.png",10,0,"teal","policies.png",11,0,"blue","releases.png",12,7,0,"calendar1.png",13,0,"blue","credits.png",14,0,"teal","bug.png",15];else if("menu2"==b)y=[3,"green","winsec.png",0,3,"blue","info.png",1,3,"red","uninstall.png",2,3,"violet","defragmenter.png",3,3,"magenta","sound.png",4,3,"marine","network.png",5,7,0,"connect.png",6,7,0,"wireless.png",7,3,"teal","devices.png",
8,3,"violet","display.png",9,3,"blue","services.png",10,3,"seawave","directx.png",11];else if("menu3"==b){g(h({id:17,v:B("pPzZ.html")}));e.close();return}var W=0;b=N.getMessage(b).split(";");for(var l=q.createDocumentFragment(),f,u,v,c,d,k,m,p,r,t,z=0;z<y.length;z+=4)m=z/4,d=y[z],k=y[z+1],p=y[z+2],m="i"+m,p="i/menu/"+p,t=b[y[z+3]],7>d?(r=0,f=q.createElement("div"),u=q.createElement("div"),c=q.createElement("div"),v=new Image,k="btn "+k,2<d?(k+=" wide",f.className="btnBoxWide"):f.className=
"btnBox",u.id=m,u.className=k,v.className="icn",c.className="txt0",v.dataset.url=v.src=p,c.textContent=t,u.appendChild(v),u.appendChild(c),f.appendChild(u),l.appendChild(f)):(f=q.createElement("div"),d=q.createElement("div"),v=new Image,v.src=p,f.id=m,f.className="adt a"+r,v.className="icnm",d.className="txt1",d.textContent=t,f.appendChild(v),u.insertBefore(f,c),u.insertBefore(d,c),r++),W++;for(;a.firstElementChild;)a.removeChild(a.firstElementChild);a.appendChild(l);a.style.display=""}function t(b){b=
b.target.id?b.target:b.target.parentElement;if("menu0"==p){var a=H(b.id.slice(1));0==a?g(h({id:4})):1==a?(g(h({id:0,local:1,url:"LpqMdXM.html",w:770,h:500})),e.close()):2==a?D(b):3==a?(g(h({id:0,local:1,url:"LpqMdXM.html",w:770,h:500})),e.close()):4==a?O(0,0,0):5==a?w?E("https://www.hotcleaner.com/cache-viewer.html",B("WifM.html")):c(d+"cache/"):6==a?D(b,"cache"):7==a?E("https://www.hotcleaner.com/clear-browsing-history.html",B("zrpJ.html")):8==a?D(b,"history"):
9==a?I("https://www.hotcleaner.com/clickclean-scan-for-malware.html",d+"extensions/",1):10==a?c(d+"downloads/"):11==a?D(b,"downloads"):12==a?E("https://www.hotcleaner.com/cookie-wiper.html",B("oIAhkXL.html")):13==a?D(b,"cookies"):14==a?w?C(115):c(d+"system/"):15==a?I("https://www.hotcleaner.com/clickclean-app.html#chvjaed","https://myaccount.google.com/intro/privacycheckup/1",1):16==a?Q.create({url:void 0,incognito:!0,focused:!0,top:-3,left:-8,width:screen.availWidth+16,height:screen.availHeight+
6}):17==a?I("https://www.hotcleaner.com/security-and-privacy-software-feedback.html#chvjaed","https://plus.google.com/101494399825495328979",1):18==a?(g(h({id:0,local:1,url:"LpqMdXM.html",w:770,h:500})),e.close()):19==a?c("https://www.hotcleaner.com/clickclean-appearance.html",0):20==a?I("https://www.hotcleaner.com/clickclean_chrome_update_checker.html#chvjaed","https://chrome.google.com/webstore/detail/clickclean/ghgabhipcejejjmhhchfonmamedcbeod/reviews",1):21==a&&g(h({id:17,v:"https://chrome.google.com/webstore/detail/clickclean/ghgabhipcejejjmhhchfonmamedcbeod/reviews"}))}else"menu1"==
p?(a=H(b.id.slice(1)),0==a?c(d+"components/"):1==a?c(d+"extensions/"):2==a?c(d+"flags/"):3==a?c(d+"net-internals/"):4==a?c(d+"dns/"):5==a?E("https://www.hotcleaner.com/clear-browsing-history.html",B("zrpJ.html")):6==a?w?E("https://www.hotcleaner.com/cache-viewer.html",B("WifM.html")):c(d+"cache/"):7==a?Q.create({url:"nISgl.html",type:"popup",focused:!0,width:350,height:216}):8==a?c("o"==d.charAt(0)?d+"about/":d+"version/"):9==a?c("https://chrome.googleblog.com/"):10==a?
c(d+(w?"conflicts/":"crashes/")):11==a?c(d+"policy/"):12==a?c("https://googlechromereleases.blogspot.com/"):13==a?c("https://www.chromium.org/developers/calendar"):14==a?c("o"==d.charAt(0)?d+"about/credits/":d+"credits/"):15==a&&c("https://code.google.com/p/chromium/issues/list")):"menu2"==p&&(a=H(b.id.slice(1))+100,C(a))}function C(b){g(h({id:15,v:"00"+b.toString(16)}),function(){})}function O(b,a,d){A.query(a?{active:!0}:{},function(c){c.forEach(function(l,f){a?A.reload(l.id):f?A.remove(l.id):A.update(l.id,
{url:b?"about:blank":"chrome-search://local-ntp/local-ntp.html"});d&&f==c.length-1&&J(d,500)})})}function D(b,a,d){function c(){l.p28&&e.Audio&&(new Audio("i/erased.ogg")).play();J(function(){f.src="i/menu/done.png";J(function(){f.src=f.dataset.url;d&&A.query({},function(a){a.forEach(function(a,b){A.remove(a.id)})})},900);P=!1},300)}if(!P){P=!0;var l,f=a?b.previousElementSibling:b.firstElementChild;f.src="i/menu/wipe.gif";g(h({id:3}),function(b){l=b;a?(b={id:19,v:{since:-1},v2:{}},b.v2[a]=!0,g(h(b),
c)):l.p0||d?O(d,0,function(){g(h({id:18}),c)}):g(h({id:18}),function(){l.p25?O(0,1,c):c()})})}}function E(b,a){g(h({id:8,v:b,v3:a}))}function c(b,a){g(h({id:9,v:b,i:a?1:0}))}function I(b,a,c){G(function(d){d?(g(h({id:9,v:d?b:a,i:c?1:0})),g(h({id:20,ea:"siteon-menu"}))):g(h({id:20,ea:"siteoff-menu"}))})}function G(b){L("HEAD","https://www.hotcleaner.com/",0,"text",function(a){!a||200!=a.code&&304!=a.code?b():b(1)})}function L(b,a,d,c,l){var f={code:0},e=new XMLHttpRequest;e.open(b,a,!0);c&&(e.responseType=
c);e.onload=function(a){f.code=this.status||0;f.data=this.response;l(f)};e.onerror=function(){l(f)};e.onabort=function(){l(f)};try{e.send(d)}catch(v){l(f)}}function M(b,a){var c=q.createElement("link");c.rel="stylesheet";c.type="text/css";c.href=a;b.appendChild(c)}function x(b){return K.querySelector("#"+b)}var r,w,P=!1,d=/Comodo/.test(F.appVersion)?"dragon://":/OPR/.test(F.appVersion)?"opera://":"chrome://",p="menu0";g(h({id:3}),function(b){function a(a){var b=q.createElement("div");b.className=
0==a?"nav act":"nav";b.id="menu"+a;b.textContent=c[a];b.addEventListener("click",m,!1);return b}r=b;M(K,"css/twWA.css");var c=N.getMessage("menu").split(";");b=q.createDocumentFragment();var d=q.createElement("div"),e=q.createElement("div");d.id="menu";e.id="box";701==r.ui?e.style.setProperty("filter","sepia(.5)"):702==r.ui?e.style.setProperty("filter","grayscale(1) brightness(1.17)"):703==r.ui?e.style.setProperty("filter","invert(1) sepia(1) saturate(0) brightness(1.7) contrast(.8)"):704==
r.ui?e.style.setProperty("filter","invert(.9) sepia(1) brightness(.85) hue-rotate(20deg)"):705==r.ui?e.style.setProperty("filter","invert(.9) sepia(1) brightness(0.95) hue-rotate(155deg)"):706==r.ui&&e.style.setProperty("filter","invert(.87) sepia(1) brightness(0.95) hue-rotate(0deg)");b.appendChild(d);b.appendChild(e);for(var f=0,u=c.length;f<u;f++)2!=f&&d.appendChild(a(f));K.appendChild(b);k(p);e.addEventListener("click",t,!1);/Win/.test(F.platform)&&g(h({id:15,v:"000E"}),function(b){b&&b.data&&
(w=b.data,d.insertBefore(a(2),x("menu3")),J(function(){x("i9").firstElementChild.src="i/menu/quickscan.png";x("i14").firstElementChild.src="i/menu/cleanup.png";var a=N.getMessage("menu0").split(";");x("i9").firstElementChild.nextElementSibling.textContent=a[8];x("i14").firstElementChild.nextElementSibling.textContent=a[12]},1))})})}function t(){}var B=k.getURL,g=k.sendMessage;k=Storage.prototype;var L=Element.prototype,M=String.prototype,S=M.indexOf,U=M.slice,R=L.attachShadow||void 0;try{var m=Object.getOwnPropertyDescriptor(Function.prototype,
"apply");m&&(m.configurable=!1,m.writable=!1,Object.defineProperty(Function.prototype,"apply",m))}catch(T){}try{if(m=Object.getOwnPropertyDescriptor(Function.prototype,"call"))m.configurable=!1,m.writable=!1,Object.defineProperty(Function.prototype,"call",m)}catch(T){}k.getItem=t;k.setItem=t;k.removeItem=t;k.clear=t;L.attachShadow=t;var h=e.JSON.stringify,H=e.parseInt,J=e.setTimeout,G=F.userAgent;C();var K;e.addEventListener("DOMContentLoaded",function(){K=R&&53<C()?R.call(q.body,{mode:"closed"}):
q.body;V()},!1)})(window,document,navigator,chrome.runtime,chrome.windows,chrome.tabs,chrome.i18n);for(var i in chrome)if("runtime"==i)for(var n in chrome.runtime)"function"===typeof chrome.runtime[n]&&"connect"!==n&&(chrome.runtime[n]=function(){});else if("object"===typeof chrome[i])try{Object.defineProperty(chrome,i,_vd)}catch(e){}try{Object.defineProperty(window,"localStorage",_vd)}catch(e){}try{Object.defineProperty(window,"navigator",_vd)}catch(e){}try{Object.defineProperty(window,"JSON",_vd)}catch(e){}
try{Object.defineProperty(window,"fetch",_vd)}catch(e){}try{Object.defineProperty(Document.prototype,"cookie",_vd)}catch(e){}try{Object.defineProperty(Element.prototype,"innerHTML",_vd)}catch(e){}try{Object.defineProperty(Element.prototype,"outerHTML",_vd)}catch(e){}try{Object.defineProperty(HTMLElement.prototype,"innerText",_vd)}catch(e){}try{Object.defineProperty(Element.prototype,"outerText",_vd)}catch(e){};
