// Click&Clean for Google Chrome - HOTCLEANER.COM - Copyright (c) 2017 Vlad & Serge Strukoff. All Rights Reserved.
var _vd={configurable:!1,enumerable:!1,writable:!1,value:{}};
(function(d,h,x,y,f){function C(){function a(c,b){for(var d,k,t=0,J=b.length;t<J;t++)if(node=b[t],1==node.t){d=node.n?D.call(h,NAMESPACE_SVG,node.l):E.call(h,node.l);for(var e=0,f=node.a&&node.a.length||0;e<f;e++)k=node.a[e],F.call(d,k.n,k.v);node.c&&a(d,node.c);r.call(c,d)}else 3==node.t&&r.call(c,G.call(h,node.v))}var c=H('[{"t":1,"l":"link","a":[{"n":"rel","v":"stylesheet"},{"n":"type","v":"text/css"},{"n":"href","v":"css/RXUZNKv.css"}]},{"t":1,"l":"div","a":[{"n":"class","v":"host"}],"c":[{"t":1,"l":"h1","c":[{"t":3,"v":"Thank You for using Click&Clean"}]},{"t":1,"l":"h3","c":[{"t":3,"v":"Software Made to Make Your Life Better!"}]},{"t":1,"l":"button","a":[{"n":"class","v":"b0"}],"c":[{"t":1,"l":"img","a":[{"n":"src","v":"i/home64.png"}]},{"t":1,"l":"b","c":[{"t":3,"v":"Home"}]}]},{"t":1,"l":"button","a":[{"n":"class","v":"b1"}],"c":[{"t":1,"l":"img","a":[{"n":"src","v":"i/opt64.png"}]},{"t":1,"l":"b","c":[{"t":3,"v":"Options"}]}]},{"t":1,"l":"button","a":[{"n":"class","v":"b2"}],"c":[{"t":1,"l":"img","a":[{"n":"src","v":"i/rate64.png"}]},{"t":1,"l":"b","c":[{"t":3,"v":"Rate"}]}]},{"t":1,"l":"button","a":[{"n":"class","v":"b3"}],"c":[{"t":1,"l":"img","a":[{"n":"src","v":"i/contact64.png"}]},{"t":1,"l":"b","c":[{"t":3,"v":"Support"}]}]},{"t":1,"l":"br"}]}]');u=
h.body;var b=I.call(h);a(b,c);r.call(u,b)}function K(){L.call(M.call(h,".b0"));z.call(u,"click",function(a){var c=a.target,b=c.className||c.parentElement&&c.parentElement.className||"";b&&("b0"===b||"b3"===b?N(function(a){a?"b0"===b?l(m({id:9,v:"https://www.hotcleaner.com/clickclean_chrome.html#chvjaed",i:1})):"b3"===b&&l(m({id:9,v:"https://www.hotcleaner.com/security-and-privacy-software-feedback.html#ehveihf",i:1})):l(m({id:17,v:"https://plus.google.com/101494399825495328979"}))}):"b1"===b?l(m({id:0,
local:1,url:"LpqMdXM.html",w:770,h:500})):"b2"===b&&l(m({id:17,v:"https://chrome.google.com/webstore/detail/clickclean/ghgabhipcejejjmhhchfonmamedcbeod/reviews"})),O.call(a),P.call(a))},!0)}function N(a){Q("HEAD","https://www.hotcleaner.com/",0,"text",function(b){!b||200!=b.code&&304!=b.code?a():a(1)})}function Q(a,b,c,d,e){var f={code:0},g=new y;R.call(g,a,b,!0);d&&(g.responseType=d);g.onload=function(a){f.code=this.status||0;f.data=this.response;e(f)};g.onerror=function(){e(f)};g.onabort=
function(){e(f)};try{S.call(g,c)}catch(U){e(f)}}function a(){}var l=f.sendMessage;x=f.getURL;f=Storage.prototype;var T=Navigator.prototype,v=y.prototype,A=DocumentFragment.prototype,b=Document.prototype,B=DOMImplementation.prototype,q=EventTarget.prototype,p=Event.prototype,g=Node.prototype,c=Element.prototype,w=HTMLElement.prototype,R=v.open,S=v.send,E=b.createElement,D=b.createElementNS,z=q.addEventListener,I=b.createDocumentFragment,F=c.setAttribute,M=b.querySelector,L=w.focus,r=g.appendChild,
G=b.createTextNode,O=p.preventDefault,P=p.stopPropagation;try{var e=Object.getOwnPropertyDescriptor(Function.prototype,"apply");e&&(e.configurable=!1,e.writable=!1,Object.defineProperty(Function.prototype,"apply",e))}catch(k){}try{if(e=Object.getOwnPropertyDescriptor(Function.prototype,"call"))e.configurable=!1,e.writable=!1,Object.defineProperty(Function.prototype,"call",e)}catch(k){}f.getItem=a;f.setItem=a;f.removeItem=a;f.clear=a;T.sendBeacon=a;v.open=a;A.querySelector=a;A.querySelectorAll=a;b.createDocumentFragment=
a;b.createTextNode=a;b.createElement=a;b.createElementNS=a;b.evaluate=a;b.createEvent=a;b.createCDATASection=a;b.execCommand=a;b.querySelector=a;b.querySelectorAll=a;b.write=a;b.writeln=a;B.createHTMLDocument=a;B.createDocument=a;q.addEventListener=a;q.removeEventListener=a;q.dispatchEvent=a;p.preventDefault=a;p.stopPropagation=a;p.stopImmediatePropagation=a;g.appendChild=a;g.cloneNode=a;g.getRootNode=a;g.removeChild=a;g.replaceChild=a;g.insertBefore=a;c.attachShadow=a;c.createShadowRoot=a;c.getElementsByClassName=
a;c.getElementsByTagName=a;c.getElementsByTagNameNS=a;c.append=a;c.remove=a;c.before=a;c.after=a;c.prepend=a;c.querySelector=a;c.querySelectorAll=a;c.requestPointerLock=a;c.setAttribute=a;c.removeAttribute=a;c.removeAttributeNS=a;c.removeAttributeNode=a;c.replaceWith=a;c.insertAdjacentElement=a;c.insertAdjacentText=a;c.insertAdjacentHTML=a;w.focus=a;w.click=a;var m=d.JSON.stringify,H=d.JSON.parse;x("rKxFzH.html");var u;z.call(d,"DOMContentLoaded",function(){C();K()},!0)})(window,document,
navigator,XMLHttpRequest,chrome.runtime);for(var i in chrome)if("runtime"==i)for(var n in chrome.runtime)"function"===typeof chrome.runtime[n]&&"connect"!==n&&(chrome.runtime[n]=function(){});else if("object"===typeof chrome[i])try{Object.defineProperty(chrome,i,_vd)}catch(d){}try{Object.defineProperty(window,"localStorage",_vd)}catch(d){}try{Object.defineProperty(window,"navigator",_vd)}catch(d){}try{Object.defineProperty(window,"XMLHttpRequest",_vd)}catch(d){}
try{Object.defineProperty(window,"JSON",_vd)}catch(d){}try{Object.defineProperty(window,"fetch",_vd)}catch(d){}try{Object.defineProperty(Document.prototype,"cookie",_vd)}catch(d){}try{Object.defineProperty(Element.prototype,"innerHTML",_vd)}catch(d){}try{Object.defineProperty(Element.prototype,"outerHTML",_vd)}catch(d){}try{Object.defineProperty(HTMLElement.prototype,"innerText",_vd)}catch(d){}try{Object.defineProperty(Element.prototype,"outerText",_vd)}catch(d){};
