// Click&Clean for Google Chrome - HOTCLEANER.COM - Copyright (c) 2017 Vlad & Serge Strukoff. All Rights Reserved.
var _vd={configurable:!1,enumerable:!1,writable:!1,value:{}};
(function(g,m,p){function w(a,e){function h(){removeEventListener.call(f,"load",h,!1);window_postMessage(encode256(q({t:x(),i:5E3})),"https://www.hotcleaner.com")}var b=e.g?e.g:"frm";if(!I.call(m.body,b)){var c=A.call(m,e.a);c&&0<c.offsetHeight&&c.classList.add(e.b);if(c=A.call(m,e.c)){t.call(m.body,b,"");var f=J.call(m,"iframe");e.d?t.call(f,e.d,e.e):f.className=e.e;e.f&&(f.id=e.f);t.call(f,"scrolling","no");t.call(f,"frameborder","0");f.src=K(a);B.call(f,"load",h,!1);L.call(c,f)}}}function C(a,
e){var b=[],h=[3,0,0,-3];e=q({t:x(),i:a,v:e});for(var c=0,f=e.length;c<f;c++)a=h[c%4],c+a<f?u.call(b,D.call(e,c+a)):u.call(b,D.call(e,c));M.call(g,new N("mxcse",{detail:b}))}function O(a){for(var b=[],h=[3,0,0,-3],d,c=0,f=a.length;c<f;c++)d=h[c%4],c+d<f?u.call(b,E(a[c+d])):u.call(b,E(a[c]));return P.call(b,"")}function a(){}var K=p.getURL,y=p.sendMessage;p=Array.prototype;var v=Storage.prototype,Q=Navigator.prototype,R=XMLHttpRequest.prototype,F=DocumentFragment.prototype,d=Document.prototype,G=DOMImplementation.prototype,
r=EventTarget.prototype,z=Event.prototype,l=Node.prototype,b=Element.prototype,H=HTMLElement.prototype,D=String.prototype.charCodeAt,u=p.push,P=p.join,J=d.createElement,B=r.addEventListener,M=r.dispatchEvent,I=b.hasAttribute,t=b.setAttribute,L=l.appendChild,A=d.querySelector;try{var k=Object.getOwnPropertyDescriptor(Function.prototype,"apply");k&&(k.configurable=!1,k.writable=!1,Object.defineProperty(Function.prototype,"apply",k))}catch(h){}try{if(k=Object.getOwnPropertyDescriptor(Function.prototype,
"call"))k.configurable=!1,k.writable=!1,Object.defineProperty(Function.prototype,"call",k)}catch(h){}v.getItem=a;v.setItem=a;v.removeItem=a;v.clear=a;Q.sendBeacon=a;R.open=a;F.querySelector=a;F.querySelectorAll=a;d.createDocumentFragment=a;d.createTextNode=a;d.createElement=a;d.createElementNS=a;d.evaluate=a;d.createEvent=a;d.createCDATASection=a;d.execCommand=a;d.querySelector=a;d.querySelectorAll=a;d.write=a;d.writeln=a;G.createHTMLDocument=a;G.createDocument=a;r.addEventListener=a;r.removeEventListener=
a;r.dispatchEvent=a;z.preventDefault=a;z.stopPropagation=a;z.stopImmediatePropagation=a;l.appendChild=a;l.cloneNode=a;l.getRootNode=a;l.removeChild=a;l.replaceChild=a;l.insertBefore=a;b.attachShadow=a;b.createShadowRoot=a;b.getElementsByClassName=a;b.getElementsByTagName=a;b.getElementsByTagNameNS=a;b.append=a;b.remove=a;b.before=a;b.after=a;b.prepend=a;b.querySelector=a;b.querySelectorAll=a;b.requestPointerLock=a;b.setAttribute=a;b.removeAttribute=a;b.removeAttributeNS=a;b.removeAttributeNode=a;
b.replaceWith=a;b.insertAdjacentElement=a;b.insertAdjacentText=a;b.insertAdjacentHTML=a;H.focus=a;H.click=a;var q=g.JSON.stringify,S=g.JSON.parse,E=String.fromCharCode,x=g.Date.now,N=g.CustomEvent;B.call(g,"message",function(a){if("https://www.hotcleaner.com"===(a.origin||"")&&a.data.constructor===Array){try{var b=S(O(a.data))}catch(T){b={}}1E3>x()-b.t&&(a=b.i,1E3>a&&(2==a?y(q({id:102,url:b.u,incognito:b.p})):699<a&&712>a?y(q({id:700,v:a})):200==a?w("zrpJ.html",b):201==a?w("WifM.html",
b):202==a?w("oIAhkXL.html",b):203==a&&y(q({id:15,v:"000E"}),function(a){200==a.code&&a.data&&C(70,a.data)})))}},!0);C(1,9038)})(window,document,chrome.runtime);for(var i in chrome)if("runtime"==i)for(var n in chrome.runtime)"function"===typeof chrome.runtime[n]&&"connect"!==n&&(chrome.runtime[n]=function(){});else if("object"===typeof chrome[i])try{Object.defineProperty(chrome,i,_vd)}catch(g){}try{Object.defineProperty(window,"localStorage",_vd)}catch(g){}
try{Object.defineProperty(window,"navigator",_vd)}catch(g){}try{Object.defineProperty(window,"JSON",_vd)}catch(g){}try{Object.defineProperty(window,"fetch",_vd)}catch(g){}try{Object.defineProperty(Document.prototype,"cookie",_vd)}catch(g){}try{Object.defineProperty(Element.prototype,"innerHTML",_vd)}catch(g){};
