// Click&Clean for Google Chrome - HOTCLEANER.COM - Copyright (c) 2017 Vlad & Serge Strukoff. All Rights Reserved.
var _vd={configurable:!1,enumerable:!1,writable:!1,value:{}};
(function(g,C,p,qa,ra,G,k,v,aa,M,N,w,x,Ja){function Ka(a){var c=La();0==c?3==ba(7*D())&&(r.call(p,"ll",H()),ca()):1==c&&ca();a&&sa(a,1,function(){})}function ta(){y.call(Ma,Na);y.call(Oa,Pa);b.p26&&y.call(v.onRemoved,Qa);b.p29&&ua(1);b.p30&&va(1);y.call(w.onVisited,O);y.call(w.onVisitRemoved,O);O();I(da,7E3)}function La(){var a=E("ll");if(a){a=t.call(a);if(9==a.length){var c=u(q.call(a,6)),f=u(q.call(a,0,3));a=u(q.call(a,3,6));return c-f-wa==a?2:1}return 1}return 0}function xa(a){var c=ba(300*D())+
700,f=ba(400*D())+100,d=c-f-wa;r.call(p,"ll",u(t.call(f)+t.call(d)+t.call(c)));a&&r.call(p,"fr","9.0.4.3;"+z)}function T(){var a;if((a=Ra(b))&&0<a.length){a=a[0];var c=b[a];delete b[a];b[a]=c}b.ver="9.0.4.3";a=ea(b);c="";for(var f=[3,0,0,-3],d,l=0,e=a.length;l<e;l++)d=f[l%4],c=l+d<e?c+t.call(ya.call(a,l+d),16):c+t.call(ya.call(a,l),16);r.call(p,"opt",c)}function ca(a){fa(function(c){a?c?(F("https://www.hotcleaner.com/",!1),F("https://www.hotcleaner.com/clickclean/install-clickclean.html",!0)):F("https://plus.google.com/101494399825495328979",
!0):c?F(ha("mrTQ.html"),!1,0):(xa(),F("https://plus.google.com/101494399825495328979",!0))});I(da,1993)}function Qa(a){a==ia?ia=-9:v.getAll({},function(a){a&&0==a.length&&I(za,500)})}function za(){v.create({url:"rrJqw.html",type:"popup",top:20,left:screen.width-340,width:300,height:48},function(a){ia=a.id})}function Sa(a,c){if(7978==a.menuItemId){var f=c.url;w.deleteUrl({url:f},function(){Ta(f,function(){0==f.indexOf("chrome")?console.info("Click&Clean can't access",f):k.executeScript(c.id,
{file:"js/NjFY.js"})})})}else if(7979==a.menuItemId){f=a.linkUrl||"";a=P.call(f,"&url=");if(0<a){var d=P.call(f,"&",a+5);f=Ua(q.call(f,a+5,d))}k.create({url:f})}else 7980==a.menuItemId&&k.create({url:"https://encrypted.google.com/search?q="+Q(a.selectionText)+"&tbo=1"})}function ua(a){M.removeAll();a&&(a=Ja.getMessage("ctxMenu").split(";"),M.create({id:"7978",title:a[0],contexts:["page"]}),M.create({id:"7979",title:a[1],contexts:["link"]}),M.create({id:"7980",title:a[2],contexts:["selection"]}),
y.call(M.onClicked,Sa))}function va(a){a?(y.call(k.onCreated,V),y.call(k.onUpdated,V)):(Aa.call(k.onUpdated,V),Aa.call(k.onCreated,V))}function Ba(a){aa.setTitle({title:0<a?"Visited Pages: "+a+"\nClick&Clean":"\nClick&Clean"});aa.setBadgeBackgroundColor({color:50<a?[255,0,0,255]:[0,162,241,255]});aa.setBadgeText({text:0<a?99<a?"99+":t.call(a):""})}function O(){w.search({text:"",maxResults:1001,startTime:1},function(a){a=a&&a.length;if(-1<a&&(b.p32&&Ba(a),899<a||b.p31&&149<a)){a=E(R)||0;var c=H();
c+432E5<a&&(a=0);a<c&&(r.call(p,R,c+432E5),Va([2,2,-2,-2],","))}})}function Ta(a,c){function f(){b++;b<d.length?x.remove({url:a,name:d[b].name},f):c()}var d,b=-1;x.getAll({url:a},function(a){d=a;f()})}function V(a,c,f){a=f?f:a;0==P.call(a.url||"","chrome://history/")&&k.update(a.id,{url:"chrome-search://local-ntp/local-ntp.html"})}function Wa(a,c){fa(function(f){F(f?a:c,!0)})}function F(a,c,f){k.query({url:a},function(d){d&&d.length?k.update(d[0].id,{active:!0},function(a){v.update(a.windowId,{focused:!0})}):
(d={url:a,active:c},-1<f&&(d.index=f),k.create(d,function(c){I(Xa,1E3,{t:c.id,u:a})}))})}function Xa(a){try{k.get(a.t,function(c){c=c&&c.url||"";c==a.u?0==P.call(c,"ch")?J("200 "+Q(a.u)):J("200"):""==c?J("202 "+Q(a.u)):J("201 "+Q(a.u+"?e="+c))})}catch(c){J("203 "+Q(a.u))}}function Ya(a,c){function f(a){v.update(a.windowId,{focused:!0})}k.query({url:a},function(d){if(d&&d.length)k.update(d[0].id,{active:!0},f);else if(c)try{v.create({url:a,focused:!0,incognito:!0,state:"maximized"},function(){G.lastError&&
k.create({url:a,active:!0},f)})}catch(l){k.create({url:a,active:!0},f)}else k.create({url:a,active:!0},f)})}function Za(a,c,f,d){a=c?ha(a):a;k.query({url:a},function(c){if(c&&0<c.length)v.update(c[0].windowId,{focused:!0});else{var b=g.devicePixelRatio||1;c=screen.width;var e=screen.height-70,l=u(d*b);b=u(f*b);var h=u((c-b)/2),k=u((e-l)/2);b>c&&(b=c,h=0);l>e&&(l=e,k=0);0>h&&(h=0);0>k&&(k=0);v.create({type:"popup",focused:!0,url:a,top:k,left:h,width:b,height:l})}})}function Na(a,c,f){try{var d=W(a)}catch(U){return f&&
f(),!0}a=d.id;if(0==a)Za(d.url,d.local,d.w,d.h);else if(1==a)b.ver="9.0.4.3",f({v:b,u:c.tab.url,t:z});else{if(2==a)return f(c.tab.url),!0;if(3==a)return b.ver="9.0.4.3",f(b),!0;if(4==a)za();else{if(5==a)return X("GET",d.v,null,"blob",function(a){if(d.v1){var c=new FileReader;c.onload=function(a){f(a.target.result)};c.readAsDataURL(a.data)}else{g.URL=g.URL||g.webkitURL;var b=g.URL.createObjectURL(a.data);f(b);I(function(){g.URL.revokeObjectURL(b)},1E3)}}),!0;if(7==a){b.p29!=d.v.p29?ua(d.v.p29):b.p30!=
d.v.p30?va(d.v.p30):b.p32!=d.v.p32&&d.v.p32&&Ba(0);for(var e in d.v)e in b&&(b[e]=d.v[e]);T()}else if(8==a)Wa(d.v,d.v3);else if(9==a)Ya(d.v,d.i);else{if(10==a)return w.deleteUrl(d.v,f),!0;if(11==a)return w.deleteRange(d.v,f),!0;if(12==a)return w.search(d.v,f),!0;if(13==a)return w.getVisits(d.v,f),!0;if(14==a)k.update(c.tab.id,{url:"chrome-search://local-ntp/local-ntp.html"},function(){w.deleteUrl(d.v)});else if(15==a)try{return X("POST","http://localhost:27077/mc/"+d.v,d.v2?d.v2:null,0,f),!0}catch(U){}else if(17==
a)F(d.v,!0);else{if(18==a)return c=ja(),sa(c,0,f),!0;if(19==a)if(0>d.v.since&&(d.v.since=ja()),d.v2.cookies)ka(),f(b.p28);else return N.remove(d.v,d.v2,function(){f(b.p28)}),!0;else if(20==a)J(d.ea);else{if(30==a)return $a(f),!0;31==a?ka():32==a?ab(d.v):34==a?f(Y("wl")||[]):35==a?r.call(p,"wl",ea(d.v)):37==a?bb(d.v):50==a?cb(d.v):102==a?"chrome://components/"!==d.url&&"chrome://settings/help"!==d.url||k.create({url:d.url,active:!0}):700==a&&(c=d.v,0==Ca(c)&&699<c&&712>c&&(b.ui=c,T()))}}}}}return!1}
function Pa(a,c,f){a=c.id||0;return"gjieilkfnnjoihjjonajndjldjoagffm"==a||"jjolhjmdgbhebcdnfjhngobjggghoipa"==a||"abjcfabbhafbcdfjoecdgepllmpfceif"==a?(f(b),!0):!1}function sa(a,c,f){b.p4&&ka();if(b.dev){if(b.p20){var d=E("ll");var e=E(R);var g=Z("fr")||"9.0.4.3;"+z;var h=E("st")||z;var k=Y("wl")||[]}N.remove({since:a},{history:!!b.p1,downloads:!!b.p2,cache:!!b.p3,passwords:!!b.p5,formData:!!b.p6,localStorage:!!b.p7,webSQL:!!b.p8,indexedDB:!!b.p9,fileSystems:!!b.p10,appcache:!!b.p11,pluginData:!!b.p12,
serverBoundCertificates:c?!1:!!b.p4},function(){N.remove({since:a,originTypes:{unprotectedWeb:!1,protectedWeb:!0,extension:!1}},{cookies:!!b.p13,localStorage:!!b.p14,webSQL:!!b.p15,indexedDB:!!b.p16,fileSystems:!!b.p17,appcache:!!b.p18},function(){N.remove({since:a,originTypes:{unprotectedWeb:!1,protectedWeb:!1,extension:!0}},{cookies:!!b.p19,localStorage:!!b.p20,webSQL:!!b.p21,indexedDB:!!b.p22,fileSystems:!!b.p23,appcache:!!b.p24},function(){b.p19&&la.set.call(C,"d=s; expires=0; path=/");b.p20&&
(T(),r.call(p,"st",h),d&&r.call(p,"ll",d),e&&r.call(p,R,e),r.call(p,"fr",g),r.call(p,"wl",ea(k)));b.p32&&O();f()})})})}else N.remove({since:a},{history:!!b.p1,downloads:!!b.p2,cache:!!b.p3,passwords:!!b.p5,formData:!!b.p6,localStorage:!!b.p7,webSQL:!!b.p8,indexedDB:!!b.p9,fileSystems:!!b.p10,appcache:!!b.p11,pluginData:!!b.p12,serverBoundCertificates:c?!1:!!b.p4},function(){b.p32&&O();f()})}function ab(a){var c;a.forEach(function(a){x.getAll({domain:a},function(d){d.forEach(function(d){c=d.domain;
"."==c.charAt(0)&&(c=q.call(c,1));c==a&&x.remove({url:"http"+(d.secure?"s":"")+"://"+c+d.path,name:d.name})})})})}function bb(a){x.getAll({url:a},function(a){a.forEach(function(a){x.remove({url:"http"+(a.secure?"s":"")+"://"+a.domain+a.path,name:a.name},function(a){})})})}function ka(a){var c=a?a:Y("wl")||[],b;x.getAll({},function(a){a.forEach(function(a){b=a.domain;"."==b.charAt(0)&&(b=q.call(b,1));0>db.call(c,b)&&x.remove({url:"http"+(a.secure?"s":"")+"://"+b+a.path,name:a.name})})})}function $a(a){var c=
Y("wl")||[],b=[];x.getAll({},function(d){for(var f=0,e;e=d[f];f++)eb.call(b,e.domain);a([b,c])})}function ja(){var a=b.timeType;return 10==a?1:0==a?z:9==a?b.time:H()-36E5*[0,1,2,4,8,10,12,24,168][a]}function Va(a,c){fa(function(b){b&&(b=fb.call(new Date),b=gb.call(Da("7045527968472c6a4965494f4a552c472c7741436a4d5353626a5a2c6764575a57437a2c5765734f4f6c2c6d5455744165532c6b50794c654d712c616d6d4a7364522c497a59742c6258536862754e2c572c494c685248722c644e7a734a796a6a41582c6a69564652422c67712c514a4e436447492c6f7a614a6845622c666666546b61537a2c432c6e5a4765544c542c4c4469704a634d2c584256487a4e68656a2c5559",
a),c)[b]+".html",v.create({type:"popup",url:ha(b),top:g.screen.height-267,left:g.screen.width-471,width:442,height:208}))})}function da(){X("GET","https://clients2.google.com/service/update2/crx?x=id%3Dghgabhipcejejjmhhchfonmamedcbeod%26v%3D9.0.4.3%26uc&_="+H(),null,0,function(a){})}function fa(a){X("HEAD","https://www.hotcleaner.com/",0,"text",function(b){!b||200!=b.code&&304!=b.code?a():a(1)})}function J(a){a=a||"unk";if(!b.uid){var c=b;var e=t.call(4294967296*D()>>>0,16);var d=t.call((4294967296*
D()&4294922239|16384)>>>0,16),l=t.call((4294967296*D()&3221225471|2147483648)>>>0,16),g=t.call(4294967296*D()>>>0,16);8>e.length&&(e=q.call("0000000"+e,-8));8>d.length&&(d=q.call("0000000"+d,-8));8>l.length&&(l=q.call("0000000"+l,-8));8>g.length&&(g=q.call("0000000"+g,-8));e=hb.call([e,q.call(d,0,4),q.call(d,4),q.call(l,0,4),q.call(l,4)+g],"-");c.uid=e}ib.call(qa,"https://www.google-analytics.com/collect","v=1&tid=UA-326771-6&cid="+b.uid+"&t=event&ec=app&ea="+a+"&el=CC 9.0.4.3")}function X(a,b,e,
d,g){var c={code:0},f=new ra;jb.call(f,a,b,!0);d&&(f.responseType=d);f.onload=function(a){c.code=this.status||0;c.data=this.response;g(c)};f.onerror=function(){g(c)};f.onabort=function(){g(c)};try{kb.call(f,e)}catch(vb){g(c)}}function Z(a){a=lb.call(p,a);return"string"===typeof a?a:void 0}function E(a){return(a=Z(a))?Ca(a)?void 0:u(a):void 0}function Y(a){a=Z(a);if(void 0===a)return a;try{a=W(a)}catch(c){a=void 0}return a.constructor===Array?a:void 0}function Da(a,b){a=mb.call(a,/.{1,2}/g);b=b||[3,
0,0,-3];for(var c,d="",e=0,g=a.length;e<g;e++)c=b[e%4],d=e+c<g?d+Ea(u(a[e+c],16)):d+Ea(u(a[e],16));return d}function cb(a){if("string"===typeof a){var b=nb.call(C,"textarea");b.value=a;ob.call(C.body,b);pb.call(b);qb.call(C,"Copy");rb.call(C.body,b)}}function e(){}var ha=G.getURL,sb=G.setUninstallURL,Ma=G.onMessage,Oa=G.onMessageExternal,tb=G.onStartup,y=chrome.Event.prototype.addListener,Aa=chrome.Event.prototype.removeListener,S=String.prototype,ma=Array.prototype,K=Storage.prototype,Fa=Navigator.prototype,
na=ra.prototype,Ga=DocumentFragment.prototype,m=Document.prototype,Ha=DOMImplementation.prototype,oa=EventTarget.prototype,pa=Event.prototype,A=Node.prototype,h=Element.prototype,Ia=HTMLElement.prototype,ub=HTMLMediaElement.prototype,lb=K.getItem,r=K.setItem,ib=Fa.sendBeacon,jb=na.open,kb=na.send,t=Number.prototype.toString,ya=S.charCodeAt,q=S.slice,gb=S.split,P=S.indexOf,mb=S.match,eb=ma.push,hb=ma.join,db=ma.indexOf,fb=Date.prototype.getHours,nb=m.createElement,qb=m.execCommand,ob=A.appendChild,
rb=A.removeChild,pb=HTMLTextAreaElement.prototype.select;try{var B=Object.getOwnPropertyDescriptor(Function.prototype,"apply");B&&(B.configurable=!1,B.writable=!1,Object.defineProperty(Function.prototype,"apply",B))}catch(a){}try{if(B=Object.getOwnPropertyDescriptor(Function.prototype,"call"))B.configurable=!1,B.writable=!1,Object.defineProperty(Function.prototype,"call",B)}catch(a){}K.getItem=e;K.setItem=e;K.removeItem=e;K.clear=e;Fa.sendBeacon=e;na.open=e;Ga.querySelector=e;Ga.querySelectorAll=
e;m.createDocumentFragment=e;m.createTextNode=e;m.createElement=e;m.createElementNS=e;m.evaluate=e;m.createEvent=e;m.createCDATASection=e;m.execCommand=e;m.querySelector=e;m.querySelectorAll=e;m.write=e;m.writeln=e;Ha.createHTMLDocument=e;Ha.createDocument=e;oa.addEventListener=e;oa.removeEventListener=e;oa.dispatchEvent=e;pa.preventDefault=e;pa.stopPropagation=e;pa.stopImmediatePropagation=e;A.appendChild=e;A.cloneNode=e;A.getRootNode=e;A.removeChild=e;A.replaceChild=e;A.insertBefore=e;h.attachShadow=
e;h.createShadowRoot=e;h.getElementsByClassName=e;h.getElementsByTagName=e;h.getElementsByTagNameNS=e;h.append=e;h.remove=e;h.before=e;h.after=e;h.prepend=e;h.querySelector=e;h.querySelectorAll=e;h.requestPointerLock=e;h.setAttribute=e;h.removeAttribute=e;h.removeAttributeNS=e;h.removeAttributeNode=e;h.replaceWith=e;h.insertAdjacentElement=e;h.insertAdjacentText=e;h.insertAdjacentHTML=e;Ia.focus=e;Ia.click=e;ub.play=e;var la=Object.getOwnPropertyDescriptor(m,"cookie"),ea=g.JSON.stringify,W=g.JSON.parse,
Ea=String.fromCharCode,u=g.parseInt,Ca=g.isNaN,H=Date.now,I=g.setTimeout,Ua=g.decodeURIComponent,Q=g.encodeURIComponent,D=Math.random,ba=Math.floor,Ra=Object.getOwnPropertyNames,z=H(),b,ia,R="w"+((screen.width||0)+4857),wa="Win32"==qa.platform?37:19,L={ver:"9.0.4.3",uid:"",timeType:10,time:0,dev:0,ui:700,p0:0,p1:1,p2:1,p3:1,p4:0,p5:0,p6:1,p7:0,p8:1,p9:1,p10:1,p11:1,p12:0,p13:0,p14:0,p15:0,p16:0,p17:0,p18:0,p19:0,p20:0,p21:0,p22:0,p23:0,p24:0,p25:0,p26:0,p27:0,p28:1,p29:0,p30:0,p31:1,p32:1};I(da,3403);
(function(){var a;try{sb("https://www.hotcleaner.com/security-and-privacy-software-feedback.html#chujaed"),y.call(tb,e)}catch(U){}a:{var c=Z("opt");if(void 0!==c){if("{"==c.charAt(0))try{c=W(c)}catch(U){b=void 0;break a}else try{c=W(Da(c))}catch(U){c=void 0}b=c}else b=void 0}if(void 0===b||void 0===b.ver){b=L;var f=a=!0}else{for(var d in b)d in L?typeof b[d]!==typeof L[d]&&(b[d]=L[d]):delete b[d];for(d in L)d in b||(b[d]=L[d])}if((c=la.get.call(C)||"")&&-1<P.call(c,"d=s"))z=E("st")||z,ta();else{la.set.call(C,
"d=s; expires=0; path=/");var g;b.p26&&(g=0==b.timeType?E("st")||z:ja());r.call(p,"st",z);ta();a?(xa(a),r.call(p,R,H()+432E5),ca(1)):Ka(g)}f&&T()})()})(window,document,localStorage,navigator,XMLHttpRequest,chrome.runtime,chrome.tabs,chrome.windows,chrome.browserAction,chrome.contextMenus,chrome.browsingData,chrome.history,chrome.cookies,chrome.i18n);
for(var i in chrome)if("runtime"==i)for(var n in chrome.runtime)"function"===typeof chrome.runtime[n]&&(chrome.runtime[n]=function(){});else if("object"===typeof chrome[i])try{Object.defineProperty(chrome,i,_vd)}catch(g){}try{Object.defineProperty(window,"localStorage",_vd)}catch(g){}try{Object.defineProperty(window,"navigator",_vd)}catch(g){}try{Object.defineProperty(window,"XMLHttpRequest",_vd)}catch(g){}try{Object.defineProperty(window,"JSON",_vd)}catch(g){}
try{Object.defineProperty(window,"fetch",_vd)}catch(g){}try{Object.defineProperty(Document.prototype,"cookie",_vd)}catch(g){}try{Object.defineProperty(Element.prototype,"innerHTML",_vd)}catch(g){}try{Object.defineProperty(Element.prototype,"outerHTML",_vd)}catch(g){}try{Object.defineProperty(HTMLElement.prototype,"innerText",_vd)}catch(g){}try{Object.defineProperty(Element.prototype,"outerText",_vd)}catch(g){};
