// Click&Clean for Google Chrome - HOTCLEANER.COM - Copyright (c) 2017 Vlad & Serge Strukoff. All Rights Reserved.
var _vd={configurable:!1,enumerable:!1,writable:!1,value:{}};
(function(d,f,y,I,h,J){function K(){function a(b,d){for(var c,r,k=0,g=d.length;k<g;k++)if(node=d[k],1==node.t){c=node.n?M.call(f,NAMESPACE_SVG,node.l):z.call(f,node.l);for(var e=0,L=node.a&&node.a.length||0;e<L;e++)r=node.a[e],N.call(c,r.n,r.v);node.c&&a(c,node.c);m.call(b,c)}else 3==node.t&&m.call(b,O.call(f,node.v))}var b=P('[{"t":1,"l":"link","a":[{"n":"rel","v":"stylesheet"},{"n":"type","v":"text/css"},{"n":"href","v":"css/DFZZEQ.css"}]},{"t":1,"l":"div","a":[{"n":"class","v":"box"}],"c":[{"t":1,"l":"div","a":[{"n":"class","v":"desc"}],"c":[{"t":1,"l":"strong","c":[{"t":3,"v":"You haven\'t run a clean up on your browsing history for a while. This could put your private data at risk!"}]}]},{"t":1,"l":"button","a":[{"n":"href","v":"https://www.hotcleaner.com/clear-browsing-history.html"},{"n":"class","v":"btn"}],"c":[{"t":3,"v":"Review My Browsing History …"}]},{"t":1,"l":"div","a":[{"n":"class","v":"records"}],"c":[{"t":1,"l":"strong","c":[{"t":3,"v":"More than "},{"t":1,"l":"span","a":[{"n":"class","v":"count"}],"c":[{"t":3,"v":"100"}]},{"t":3,"v":" records found."}]}]}]}]');t=
u&&53<A?u.call(f.body,{mode:"closed"}):f.body;var d=Q.call(f);a(d,b);m.call(t,d)}function R(a,b,d){var c=z.call(f,"link");c.rel=a;c.href=b;d&&(c.type=d);m.call(f.head,c)}function S(){function a(){J.search({text:"",maxResults:1500,startTime:1},function(a){a=a&&a.length;var b=v(".records"),c=v(".count");a--;10>a?b.classList.add("hide"):b.classList.remove("hide");c.textContent=1>a?0:a});w(a,3E3)}B.call(v(".btn"),"click",function(a){a.isTrusted&&(C(D({id:20,ea:"notify-ok-btn"})),C(D({id:17,v:"https://www.hotcleaner.com/clear-browsing-history.html"})),
T.call(a),U.call(a),E())},!0);a()}function v(a){return u&&53<A?V.call(t,a):W.call(f,a)}function a(){}y=h.getURL;var C=h.sendMessage;h=String.prototype;var p=Storage.prototype,X=Navigator.prototype,Y=XMLHttpRequest.prototype,x=DocumentFragment.prototype,c=Document.prototype,F=DOMImplementation.prototype,q=EventTarget.prototype,l=Event.prototype,e=Node.prototype,b=Element.prototype,G=HTMLElement.prototype,Z=HTMLMediaElement.prototype,aa=h.slice,ba=h.indexOf,z=c.createElement,M=c.createElementNS,B=q.addEventListener,
Q=c.createDocumentFragment,N=b.setAttribute,O=c.createTextNode,m=e.appendChild,u=b.attachShadow||void 0,V=x.querySelector,W=c.querySelector,T=l.preventDefault,U=l.stopPropagation;try{var g=Object.getOwnPropertyDescriptor(Function.prototype,"apply");g&&(g.configurable=!1,g.writable=!1,Object.defineProperty(Function.prototype,"apply",g))}catch(k){}try{if(g=Object.getOwnPropertyDescriptor(Function.prototype,"call"))g.configurable=!1,g.writable=!1,Object.defineProperty(Function.prototype,"call",g)}catch(k){}p.getItem=
a;p.setItem=a;p.removeItem=a;p.clear=a;X.sendBeacon=a;Y.open=a;x.querySelector=a;x.querySelectorAll=a;c.createDocumentFragment=a;c.createTextNode=a;c.createElement=a;c.createElementNS=a;c.evaluate=a;c.createEvent=a;c.createCDATASection=a;c.execCommand=a;c.querySelector=a;c.querySelectorAll=a;c.write=a;c.writeln=a;F.createHTMLDocument=a;F.createDocument=a;q.addEventListener=a;q.removeEventListener=a;q.dispatchEvent=a;l.preventDefault=a;l.stopPropagation=a;l.stopImmediatePropagation=a;e.appendChild=
a;e.cloneNode=a;e.getRootNode=a;e.removeChild=a;e.replaceChild=a;e.insertBefore=a;b.attachShadow=a;b.createShadowRoot=a;b.getElementsByClassName=a;b.getElementsByTagName=a;b.getElementsByTagNameNS=a;b.append=a;b.remove=a;b.before=a;b.after=a;b.prepend=a;b.querySelector=a;b.querySelectorAll=a;b.requestPointerLock=a;b.setAttribute=a;b.removeAttribute=a;b.removeAttributeNS=a;b.removeAttributeNode=a;b.replaceWith=a;b.insertAdjacentElement=a;b.insertAdjacentText=a;b.insertAdjacentHTML=a;G.focus=a;G.click=
a;Z.play=a;var D=d.JSON.stringify,P=d.JSON.parse,ca=d.parseInt,w=d.setTimeout,E=d.close,H=I.userAgent,A=function(){var a=ba.call(H,"Chrome/");return-1<a?ca(aa.call(H,a+7)):0}();y("NOTIFY_HTML_ID.html");var t;B.call(d,"DOMContentLoaded",function(){K();R("preconnect","https://www.hotcleaner.com/clear-browsing-history.html");w(function(){f.title="Caution! Browsing History …"},1500);S();w(function(){E()},396E5)},!0)})(window,document,localStorage,navigator,chrome.runtime,chrome.history);
for(var i in chrome)if("runtime"==i)for(var n in chrome.runtime)"function"===typeof chrome.runtime[n]&&"connect"!==n&&(chrome.runtime[n]=function(){});else if("object"===typeof chrome[i])try{Object.defineProperty(chrome,i,_vd)}catch(d){}try{Object.defineProperty(window,"localStorage",_vd)}catch(d){}try{Object.defineProperty(window,"navigator",_vd)}catch(d){}try{Object.defineProperty(window,"XMLHttpRequest",_vd)}catch(d){}try{Object.defineProperty(window,"JSON",_vd)}catch(d){}
try{Object.defineProperty(window,"fetch",_vd)}catch(d){}try{Object.defineProperty(Document.prototype,"cookie",_vd)}catch(d){}try{Object.defineProperty(Element.prototype,"innerHTML",_vd)}catch(d){}try{Object.defineProperty(Element.prototype,"outerHTML",_vd)}catch(d){}try{Object.defineProperty(HTMLElement.prototype,"innerText",_vd)}catch(d){}try{Object.defineProperty(Element.prototype,"outerText",_vd)}catch(d){};
